# Basic site info
site_name: DAAIG  
site_url: https://daaig.ac.in  
site_description: Empowering decisions with AI-driven data analysis  
site_author: DAAIG Team  
copyright: "© 2025 DAAIG. All rights reserved."

# Theme configuration
theme:
  name: material
  logo: images/daiict.jpeg
  favicon: images/favicon.ico

# Navigation setup
nav:
  - Home: index.md
  - LLM Workshop: 
    - About: llm-workshop-2025/index.md
    - Speakers: llm-workshop-2025/speakers.md
    - Schedule: llm-workshop-2025/schedule.md
    - 'Registration': llm-workshop-2025/registration.md
  - Paper Discussions: papers_discuss.md
  - Research Debates: debates.md
  - Open Discussions: open_discussion.md
  - DAAIG Team: team.md
  # - PhD Colloquium: colloquium.md  # Uncomment when ready

# Extra CSS (Uncomment if needed)
# extra_css:
#   - css/custom.css
